name: term_glyph
version: 1.2.2
description: Useful Unicode glyphs and ASCII substitutes.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/term_glyph

environment:
  sdk: ^3.1.0

dev_dependencies:
  csv: ^6.0.0
  dart_flutter_team_lints: ^3.0.0
  dart_style: ^2.0.0
  test: ^1.16.6
