name: source_maps
version: 0.10.9

description: Library to programmatically manipulate source map files.
homepage: https://github.com/dart-lang/source_maps

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  source_span: ^1.3.0

dev_dependencies:
  source_span: ^1.5.4
  test: ^1.2.0
  term_glyph: ^1.0.0
