name: source_maps
version: 0.10.13
description: A library to programmatically manipulate source map files.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/source_maps

environment:
  sdk: ^3.3.0

dependencies:
  source_span: ^1.8.0

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  term_glyph: ^1.2.0
  test: ^1.16.0
