name: e2e_test
publish_to: none

resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  bazel_worker: any

dev_dependencies:
  cli_util: ^0.4.2
  dart_flutter_team_lints: ^3.0.0
  path: ^1.8.0
  test: ^1.16.0
