name: code_builder
version: 4.10.2
description: A fluent, builder-based library for generating valid Dart code.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/code_builder
issue_tracker: https://github.com/dart-lang/tools/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Acode_builder

environment:
  sdk: ^3.6.0

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.0.0
  collection: ^1.15.0
  matcher: ^0.12.10
  meta: ^1.3.0

dev_dependencies:
  build: ^2.0.0
  build_runner: ^2.0.3
  built_value_generator: ^8.0.0
  dart_flutter_team_lints: ^3.0.0
  dart_style: ^3.0.1
  source_gen: ^2.0.0
  test: ^1.16.0
