name: cli_config
description: >-
  A library to take config values from configuration files, CLI arguments, and
  environment variables.
version: 0.2.0
repository: https://github.com/dart-lang/tools/tree/main/pkgs/cli_config

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.0
  yaml: ^3.1.1

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  test: ^1.21.0
