name: cli_config
description: A library to take config values from configuration files, CLI arguments, and environment variables.
version: 0.1.0

repository: https://github.com/dart-lang/tools/tree/main/pkgs/cli_config

environment:
  sdk: ">=2.19.3 <4.0.0"

dependencies:
  args: ^2.4.0
  yaml: ^3.1.1

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  test: ^1.21.0
