name: browser_launcher
description: Provides a standardized way to launch web browsers for testing and tools.

version: 1.0.1-dev

homepage: https://github.com/dart-lang/browser_launcher

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  webkit_inspection_protocol: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.3
