name: unified_analytics
description: >-
  A package for logging analytics for all Dart and Flutter related tooling
  to Google Analytics.
# When updating this, keep the version consistent with the changelog and the
# value in lib/src/constants.dart.
version: 6.1.2
repository: https://github.com/dart-lang/tools/tree/main/pkgs/unified_analytics

environment:
  sdk: ^3.0.0

dependencies:
  clock: ^1.1.1
  file: '>=6.1.4 <8.0.0'
  http: '>=0.13.5 <2.0.0'
  intl: '>=0.18.0 <0.20.0'
  meta: ^1.9.0
  path: ^1.8.0

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  test: ^1.16.0
  yaml: ^3.1.1
