name: pool
version: 1.5.2
description: >-
  Manage a finite pool of resources. Useful for controlling concurrent file
  system or network requests.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/pool
issue_tracker: https://github.com/dart-lang/tools/labels/package%3Apool

environment:
  sdk: ^3.4.0

dependencies:
  async: ^2.5.0
  stack_trace: ^1.10.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  fake_async: ^1.2.0
  test: ^1.16.6
