name: graphs
version: 2.3.2-wip
description: Graph algorithms that operate on graphs in any representation
repository: https://github.com/dart-lang/tools/tree/main/pkgs/graphs

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.1.0

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  test: ^1.16.0

  # For examples
  analyzer: ^5.2.0
  path: ^1.8.0
  pool: ^1.5.0
