name: graphs
version: 2.4.0-wip
description: Graph algorithms that operate on graphs in any representation.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/graphs
issue_tracker: https://github.com/dart-lang/tools/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Agraphs

environment:
  sdk: ^3.11.0

dependencies:
  collection: ^1.19.1

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  test: ^1.29.0

  # For examples
  analyzer: ^10.0.2
  path: ^1.9.1
  pool: ^1.5.2
