name: timing
version: 1.0.2-wip
description: >-
  A simple package for tracking the performance of synchronous and asynchronous
  actions.
repository: https://github.com/dart-lang/timing

environment:
  sdk: ^3.4.0

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.0.6
  dart_flutter_team_lints: ^3.0.0
  json_serializable: ^6.0.0
  test: ^1.17.10
