name: bazel_worker
version: 1.1.2-wip
description: >-
  Protocol and utilities to implement or invoke persistent bazel workers.
repository: https://github.com/dart-lang/bazel_worker

environment:
  sdk: ^3.1.0

dependencies:
  async: ^2.5.0
  protobuf: ^3.0.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.0
