name: bazel_worker
version: 1.1.3-wip
description: >-
  Protocol and utilities to implement or invoke persistent bazel workers.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/bazel_worker
issue_tracker: https://github.com/dart-lang/tools/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Abazel_worker

environment:
  sdk: ^3.4.0

dependencies:
  async: ^2.5.0
  protobuf: ^3.0.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.0
