name: bazel_worker
version: 1.0.1-dev

description: Tools for creating a bazel persistent worker.
homepage: https://github.com/dart-lang/bazel_worker

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  async: '>=2.5.0 <3.0.0'
  protobuf: '>=2.0.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
