name: source_span
version: 1.4.1

description: A library for identifying source spans and locations.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/source_span

environment:
  sdk: '>=1.8.0 <3.0.0'

dependencies:
  charcode: ^1.0.0
  path: '>=1.2.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <2.0.0'
