name: source_span
version: 1.10.2
description: >-
  Provides a standard representation for source code locations and spans.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/source_span
issue_tracker: https://github.com/dart-lang/tools/labels/package%3Asource_span

environment:
  sdk: ^3.1.0

dependencies:
  collection: ^1.15.0
  path: ^1.8.0
  term_glyph: ^1.2.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.0
