name: package_config
version: 2.2.0
description: Support for reading and writing Dart Package Configuration files.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/package_config
issue_tracker: https://github.com/dart-lang/tools/labels/package%3Apackage_config

environment:
  sdk: ^3.4.0

dependencies:
  path: ^1.8.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.0
