name: package_config
version: 3.0.0-dev
description: Support for working with Package Configuration files.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/package_config

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0
