name: package_config
version: 2.1.1-wip
description: Support for reading and writing Dart Package Configuration files.
repository: https://github.com/dart-lang/package_config

environment:
  sdk: ^3.4.0

dependencies:
  path: ^1.8.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.0
