name: process
description: A pluggable, mockable process invocation abstraction for Dart.
version: 5.0.5
repository: https://github.com/dart-lang/tools/tree/main/pkgs/process
issue_tracker: https://github.com/dart-lang/tools/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Aprocess

topics:
  - process

environment:
  sdk: ^3.5.0

dependencies:
  file: '>=6.0.0 <8.0.0'
  path: ^1.8.0
  platform: '^3.0.0'

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.8
