name: watcher
version: 1.2.2-wip
description: >-
  A file system watcher. It monitors changes to contents of directories and
  sends notifications when files have been added, removed, or modified.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/watcher
issue_tracker: https://github.com/dart-lang/tools/labels/package%3Awatcher

environment:
  sdk: ^3.8.0

dependencies:
  async: ^2.5.0
  path: ^1.8.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  clock: ^1.1.2
  dart_flutter_team_lints: ^3.0.0
  fake_async: ^1.3.3
  test: ^1.16.6
  test_descriptor: ^2.0.0
