name: extension_discovery
description: >-
  A convention and utilities for package extension discovery.
version: 2.1.0
repository: https://github.com/dart-lang/tools/tree/main/pkgs/extension_discovery

environment:
  sdk: ^3.4.0

dependencies:
  yaml: ^3.0.0

dev_dependencies:
  collection: ^1.18.0
  dart_flutter_team_lints: ^3.0.0
  test: ^1.21.0
  test_descriptor: ^2.0.1
