# Publish the GitHub Pages site for this repo.

name: "Deploy Pages"
permissions: read-all

on:
  # Run on pushes to the default branch.
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deploy_pages.yaml'
      - 'pkgs/markdown/**'

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
      
      # Build the markdown playground.
      - run: dart pub get
        working-directory: pkgs/markdown
      - run: dart run build_runner build -o example:build --release --delete-conflicting-outputs --verbose
        working-directory: pkgs/markdown

      # Create the _site directory.
      - run: mkdir _site
      - run: cp -r pkgs/markdown/build _site/markdown

      # Deploy to GitHub Pages.
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: _site
      - uses: actions/deploy-pages@v4
