# Run against all markdown files in the latest version of packages on pub.dev
# to see if any can provoke a crash.

name: "package:markdown: crash tests"

on:
  # Run on PRs and pushes to the default branch.
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/markdown_crash_test.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/markdown_crash_test.yaml'
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'
  workflow_dispatch:
    
defaults:
  run:
    working-directory: pkgs/markdown/

jobs:
  crash-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
      - uses: dart-lang/setup-dart@e630b99d28a3b71860378cafdc2a067c71107f94
      
      - name: Install dependencies
        run: dart pub get

      - name: Run crash_test.dart
        run: dart test -P crash_test test/crash_test.dart
