name: boolean_selector
version: 2.1.0-nullsafety.2
description: >-
  A flexible syntax for boolean expressions, based on a simplified version of
  Dart's expression syntax.
homepage: https://github.com/dart-lang/boolean_selector

environment:
  # This must remain a tight constraint until nnbd is stable
  sdk: '>=2.10.0-0 <2.12.0'

dependencies:
  source_span: '>=1.8.0-nullsafety <1.8.0'
  string_scanner: '>=1.1.0-nullsafety <1.1.0'

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
  test_api: ^0.2.19-nullsafety
  test_core: ^0.3.12-nullsafety
