name: boolean_selector
version: 2.1.2
description: >-
  A flexible syntax for boolean expressions, based on a simplified version of
  Dart's expression syntax.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/boolean_selector

environment:
  sdk: ^3.1.0

dependencies:
  source_span: ^1.8.0
  string_scanner: ^1.1.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.0
