name: boolean_selector
version: 2.1.1-dev
description: >-
  A flexible syntax for boolean expressions, based on a simplified version of
  Dart's expression syntax.
repository: https://github.com/dart-lang/boolean_selector

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  source_span: ^1.8.0
  string_scanner: ^1.1.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
